services:
  mongodb:
    image: mongo:7
    container_name: portal_notas_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: portal_notas
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: portal_notas_rabbit
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Management UI (guest/guest)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mongo_data:
